################################################################################
MLI_FILE		= cordova_accelerometer.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-device-motion
################################################################################
